### ISSUE TITLE
[Opinion] Escaping escaping

### ISSUE THREAD

**Issue by svenssonaxel** [jevko/specifications#2]
This might be too late in the game, but I lament yet another generic serialization format with old-school escaping. Escaping is not ergonomic, and it is not necessary. There are several real-world examples of popular syntaxes that allow representing arbitrary data with no escaping. See [1] for more details, but essentially you find a way to introduce variety or escaping for the delimiters rather than the content.

[1] https://axelsvensson.com/escaping-escaping/

**Comment by djedr** [comment]
I appreciate your feedback. :) 

Nice article.

I have given this a lot of thought actually.

I agree that this is a very useful feature and it almost made it into the spec. I flipped back and forth many times on whether I should include it or not. It was probably the most difficult to kill.

However, I decided against it, at least because:

* It is impossible to formally define in plain *BNF.

* It complicates parser implementations.

* What goes with that is a more complex parse tree.

A basic design constraint of Jevko is that the parse tree must contain enough information to recreate the input exactly from it (it must be a concrete syntax tree) [note to self: perhaps this should be explicit in the spec]. This is because Jevko is designed to be maximally flexible, so that formats for domains with very different requirements can be built with it (e.g. markup vs data). These formats must have all the information about the input available -- they should decide whether to discard some of it as irrelevant, etc.

It is of course still possible to meet this constraint and have this feature, but in my assessment the added complexity is not worth it (another basic design constraint is maximum simplicity).

That said, if there should be demand for this feature, I might consider specifying it as an extension, in a backwards-compatible manner.

I have implemented many variants of it in the past, e.g. https://github.com/jevko/experiments#parseheredoc

If it were to be specified, it would most like look like that.

Anyway, big thanks again for your input!

I will leave this issue open for a while in case there are more comments on this topic.

**Comment by djedr** [comment]
Another thing I just remembered which pertains to this issue.

Simplicity in multiple dimensions is very important in the design of Jevko.

One aspect of it is captured by the below sentence:

> The restrictions Jevko puts on a unicode sequence are that the escape character must be followed by itself or a square bracket and that unescaped square brackets must be balanced.

This is really an exhaustive one-sentence description that would allow you to basically write a validator or generator for Jevko.

It's important to me that it stays this way, especially at this stage of adoption (or rather lack thereof). I want the initial adoption friction to be as close to zero as possible.

**Comment by svenssonaxel** [comment]
Thank you @djedr for a swift reply. Clearly, you have given this quite a bit of thought, and decided against it based on the design goals behind Jevko. Given these design goals, I think your decision is right, and my initial lamentation should be ascribed to difference in taste, as in I would personally have leaned heavier towards streamlining the use rather than implementation of a format.

It would indeed be impossible to define in plain *BNF, as are many modern, practical programming languages designed with the user in mind. Serialization formats such as JSON and XML on the other hand (I assume) can be defined in *BNF, and since Jevko probably falls in this latter category it might have been a fatal weakness to have a less neat formalism.

I've toyed with using indexed grammars for escaping-free serializations, but haven't been able to do that either. It seems, although I'm not sure, that it requires a class of grammar that supports some kind of negative operator (such as complement, difference, or does-not-contain). I'd guess such a grammar class would be undecidable in general. I guess I just wish ergonomic use wasn't in conflict with formal foundations...

**Comment by djedr** [comment]
I'm glad we are on the same page on this!

I certainly understand your concerns about ergonomy. I share them.

*BNF of course should not be the ultimate arbiter of things, but this aspect certainly plays an important role at this stage.

> I've toyed with using indexed grammars for escaping-free serializations, but haven't been able to do that either. It seems, although I'm not sure, that it requires a class of grammar that supports some kind of negative operator (such as complement, difference, or does-not-contain). I'd guess such a grammar class would be undecidable in general. I guess I just wish ergonomic use wasn't in conflict with formal foundations...

I went as far as inventing my own extensions to *BNF that would allow me to describe a self-modifying grammar. Heredocs are already kind of in the ballpark of that. That might be a good area of research, but ultimately it is at odds with the goals of simplicity and umm... approachability. Overt originality and inventiveness do not make it easier to present an idea.

Once it's established though, then maybe some room for that opens.

**Comment by djedr** [comment]
Update: after receiving more requests for this feature and finding it the most convenient and clean solution for escaping problems I recently encountered, I decided to implement it and go forward with incorporating it as an extension.

I started drafting a spec for the backwards-compatible heredoc extension here: https://github.com/jevko/specifications/blob/master/draft-extension-heredocs.md

Implemented here: https://github.com/jevko/parsejevko.js/blob/master/parseJevkoWithHeredocs.js

Used e.g. in https://github.com/jevko/jevkoconfig1.js

Example of an embedded JSON document from there:

```
some json `/json/
{ 
  "id": "b3df0d",
  "count": 55,
  "props": {
    "return code": "59503a7b",
    "status": "pending"
  },
  "associated ids": [
    "3adf7c",
    "ff0df7",
    "3aa670"
  ],
  "parent": null 
}
/json/
```

The design is:

Heredocs are delimited by `/<id>/`. Newlines inbetween the delimiters are part of the heredoc. This keeps things simple and allows for inline heredocs with the same syntax. Empty identifiers are also allowed, for short heredocs, e.g. for text which should contain square brackets without escaping.

I am pretty happy with this design, so it'll most likely stay as-is. The only thing that might change is the delimiter-delimiter character, i.e. "/" -- maybe there is a better choice. So far though I don't see it and this one works well, so most likely it will also stay.

Unless there shall be more feedback, I will soon close this issue as completed.
